TXRZ6GJ = {}
TXRZ6GJ.TXrz6GjTMQeKltEBSjcLqQc = {
    'pk',
    'haha',
    'lol',
    'xddd',
    'chocolate',
	'panickey',
	'jolmany',
	'killmenu'
}

TXRZ6GJ.Xc36ZwqaESDSNeVouPgdl0C = {
    'WEAPON_GRENADELAUNCHER',
	'WEAPON_RPG',
	'WEAPON_STINGER',
	'WEAPON_MINIGUN',
	'WEAPON_GRENADE',
	'WEAPON_STICKYBOMB',
	'WEAPON_RAILGUN',
	'WEAPON_COMPACTLAUNCHER',
	'WEAPON_PIPEBOMB',
	'WEAPON_PROXMINE',
	'WEAPON_GRENADELAUNCHER_SMOKE',
	'WEAPON_FIREWORK',
	'WEAPON_HOMINGLAUNCHER',
	'WEAPON_RAYPISTOL',
	'WEAPON_RAYCARBINE',
	'WEAPON_RAYMINIGUN',
	'WEAPON_DIGISCANNER',
}

